module.exports = {
"the vampire": "ヴァンパイア",
"vampire": "ヴァンパイア",
"buanpaia": "ヴァンパイア",
"eirianeirian": "エイリアンエイリアン",
"eirian eirian": "エイリアンエイリアン",
"alien alien": "エイリアンエイリアン",
"alienalien": "エイリアンエイリアン",
"the disappearence of hatsune miku": "初音ミクの消失",
"disappearence of hatsune miku": "初音ミクの消失",
"hatsunemikunoshoushitsu": "初音ミクの消失",
"hatsune miku no shoushitsu": "初音ミクの消失",
"happy synthesizer": "ハッピーシンセサイザ",
"happiishinsesaiza": "ハッピーシンセサイザ",
"happii shinsesaiza": "ハッピーシンセサイザ",
"happy": "Happy",
"hitomania": "人マニア",
"hito mania": "人マニア",
"kyuukurarin": "きゅうくらりん",
"kyu kurarin": "きゅうくらりん",
"kyoufuu all back": "強風オールバック",
"kyoufuu ooru bakku": "強風オールバック",
"kyoufuuoorubakku": "強風オールバック",
"mesmerizer": "メズマライザー",
"mezumaraiza": "メズマライザー",
"rabittohooru": "ラビットホール",
"rabitto hooru": "ラビットホール",
"rabbit hole": "ラビットホール",
"rensen ryouran": "恋閃繚乱",
"rensenryouran": "恋閃繚乱",
"roki": "ロキ(w/緒方恵美)",
"lost one's weeping": "ロストワンの号哭",
"lost ones weeping": "ロストワンの号哭",
"the 88s instigation": "The 88's Instigation",
"tokumei m": "匿名M",
"tokumeim": "匿名M",
"anonymous m": "匿名M",
"yoidore shirazu": "酔いどれ知らず",
"yoidoreshirazu": "酔いどれ知らず",
"bamboo sword girl": "バンブーソード・ガール",
"telecaster b boy": "テレキャスタービーボーイ",
"telecaster bboy": "テレキャスタービーボーイ",
"ekusupurouru": "エクスプロウル",
"explore": "エクスプロウル",
"positive dance time": "ポジティブ☆ダンスタイム",
"hihou! wai! neet!": "悲報！ワイ！ニート！",
"hihou wai neet": "悲報！ワイ！ニート！",
"butasanda-": "ブタサンダー",
"pig thunder": "ブタサンダー",
"buta thunder": "ブタサンダー",
"butasanda": "ブタサンダー",
"neoki yashi no ki": "寝起きヤシの木",
"neokiyashinoki": "寝起きヤシの木",
"waking yashinoki": "寝起きヤシの木",
"shukusei!! loli kami requiem": "粛聖!! ロリ神レクイエム☆",
"shukusei!! lolikami requiem": "粛聖!! ロリ神レクイエム☆",
"lolikami requiem": "粛聖!! ロリ神レクイエム☆",
"shukusei lolikami requiem": "粛聖!! ロリ神レクイエム☆",
"shukusei!! lolikami rekuiemu": "粛聖!! ロリ神レクイエム☆",
"sign wa b": "サインはB -New Arrange Ver.-",
"sain wa b": "サインはB -New Arrange Ver.-",
"sign ha b": "サインはB -New Arrange Ver.-",
"sain ha b": "サインはB -New Arrange Ver.-",
"blue impulse": "蒼い衝動",
"mikeneko rock": "三毛猫ロック",
"calico cat rock": "三毛猫ロック",
"daikenkai": "大見解",
"sakura": "桜",
"dadadadadadadadadada": "打打打打打打打打打打",
"kakumei": "革命",
"da": "打打打打打打打打打打",
"hana ranman": "華爛漫 -Flowers-",
"chikara": "チカラ",
"dandando": "男々道",
"gekkou chou": "月光蝶",
"tino's white horse": "怒れる大きな白い馬",
"kono ko no nanatsu no oiwaini": "この子の七つのお祝いに",
"for this child's seventh birthday": "この子の七つのお祝いに",
"mugen no hikari": "夢幻ノ光",
"mugen": "夢幻ノ光",
"nijiro": "虹色",
"rainbow": "虹色",
"himawari": "ヒマワリ",
"sunflower": "ヒマワリ",
"girigili burning 24h": "GIRIGILI門前雀羅",
"nadeshiko": "凛として咲く花の如く",
"nadeshiko rock": "凛として咲く花の如く",
"rin to shite saku hana no gotoku": "凛として咲く花の如く",
"yellow candy": "不沈艦CANDY",
"fuchinkan candy": "不沈艦CANDY",
"dazzlin darlin akbk mix": "Dazzlin' Darlin-秋葉工房mix-",
"kiss kiss kiss akbk mix": "KISS KISS KISS 秋葉工房 MIX",
"beautiful reciept": "ビューティフル レシート",
"beautiful receipt": "ビューティフル レシート",
"sumidagawa karenka": "隅田川夏恋歌",
"heisokuteki flation": "閉塞的フレーション",
"sumidagawa summer love song": "隅田川夏恋歌",
"heisokuteki fureeshon": "閉塞的フレーション",
"alstroemeria": "アルストロメリア (walk with you remix)",
"tsuki ni murakumo hana ni kaze": "月に叢雲華に風",
"warera kanzen muteki no idol!!": "我ら完全無敵のアイドル!!",
"tenjou no hoshi reimeiki": "天上の星 ～黎明記～",
"warera kanzen muteki no aidoru!!": "我ら完全無敵のアイドル!!",
"heavenly star dawn stories": "天上の星 ～黎明記～",
"ryouran hit chart": "繚乱ヒットチャート",
"shizuku": "雫",
"igaku": "イガク",
"medicine": "イガク",
"kouen": "紅焔",
"crimson flame": "紅焔",
"rensen ryouran": "紅焔",
"mesmerizer": "メズマライザー",
"meu meu pettantan": "めうめうぺったんたん！！",
"rabbit hole": "ラビットホール",
"chikuwa parfait": "ちくわパフェだよ☆ＣＫＰ",
"nadeshiko hinabita": "凛として咲く花の如く ～ひなビタ♪edition～",
"cirno no perfect sansuu gakuen": "チルノのパーフェクトさんすう学園",
"hoshikuzu no kirou": "星屑のキロク",
"memories of stardust": "星屑のキロク",
"cirno's perfect math academy": "チルノのパーフェクトさんすう学園",
"cirnos perfect math academy": "チルノのパーフェクトさんすう学園",
"hoshikuzu no kiroku": "星屑のキロク",
"lucky lucky": "ラキラキ",
"renkei epilogue": "恋繋エピローグ",
"rakiraki": "ラキラキ",
"ga ga ga galaxy!": "ギャ・ギャ・ギャ・ギャラクシー！",
"how to cook delicious rice and the effect of eating rice": "お米の美味しい炊き方、そしてお米を食べることによるその効果。",
"ice cream magic": "アイスクリームマジック",
"rice metal": "お米の美味しい炊き方、そしてお米を食べることによるその効果。",
"icecream magic": "アイスクリームマジック",
"nijiro no hana": "虹色の花",
"rainbow flower": "虹色の花",
"kawaikute gomen": "可愛くてごめん",
"seiten bon voyage": "晴天Bon Voyage",
"sousei note": "創世ノート",
"kiken na kajitsu": "キケンな果実",
"dangerous fruit": "キケンな果実",
"who floats": "フー・フローツ",
"colorful pastel": "からふるぱすてる",
"lovely radio": "†渚の小悪魔ラヴリィ～レイディオ†",
"mind game": "マインド・ゲーム",
"deadbowl de homerun": "デッドボヲルdeホームラン",
"how to play baseball and for its history": "野球の遊び方　そしてその歴史　～決定版～",
"THE BASEBALL": "野球の遊び方　そしてその歴史　～決定版～",
"todoroke koi no beanball": "轟け！恋のビーンボール！！",
"luckgakist": "ラクガキスト",
"rakugakisuto": "ラクガキスト",
"construction girl": "ラクガキスト",
"setsuna trip": "セツナトリップ",
"bamboosword girl": "バンブーソード・ガール",
"homeneko sensation": "ホメ猫☆センセーション",
"hanamaru pippi wa yoiko dake": "はなまるぴっぴはよいこだけ",
"edm jumpers": "イーディーエム・ジャンパーズ",
"chikuwactics": "地方創生☆チクワクティクス",
"yamato nadenade kaguya hime": "ヤマトなでなで♡かぐや姫",
"ayakashi kakushi": "妖隠し -あやかしかくし-",
"kono aozora no shita de": "この青空の下で",
"bloody tears": "Bloody Tears(IIDX EDITION)",
"endorphin": "エンドルフィン",
"crimson gate": "クリムゾンゲイト",
"wadatsumi": "海神",
"bloody tears iidx": "Bloody Tears(IIDX EDITION)",
"bloody tears iidx edition": "Bloody Tears(IIDX EDITION)",
"dokidoki ryuusei trap girl": "ドキドキ☆流星トラップガール!!",
"osenju meditation": "御千手メディテーション",
"nageki": "嘆きの樹",
"nageki no ki": "嘆きの樹",
"dopamine": "ドーパミン",
"bakunana testroyer": "爆なな☆てすとロイヤー",
"bebeatstream": "ビビットストリーム",
"totsugeki glass no kneeso hime": "突撃! ガラスのニーソ姫!",
"glass kneesocks princess": "突撃! ガラスのニーソ姫!",
"dopamine": "ドーパミン",
"tenkuu no hana": "天空の華",
"papipu yeah": "パ→ピ→プ→Yeah!",
"natsuiro diary": "夏色DIARY -DDR mix-",
"summer colored diary": "夏色DIARY -DDR mix-",
"schrodinger's cat": "シュレーディンガーの猫",
"bassdrop freaks": "ベィスドロップ・フリークス",
"mikansei": "未完成ノ蒸氣驅動乙女",
"smallest tri perfect number": "最小三倍完全数",
"ranker killer girl": "ランカーキラーガール",
"love kira splash": "ラブキラ☆スプラッシュ",
"buraikku jikorizer": "無頼ック自己ライザー",
"kyun kyun bakkyun love": "きゅん×きゅんばっきゅん☆LOVE",
"marisa stole the precious thing": "魔理沙は大変なものを盗んでいきました",
"iro wa nioedo": "色は匂へど散りぬるを",
"no plan days": "ノープラン・デイズ",
"kyousui ichika": "狂水一華",
"take me to the tokyo disco": "私をディスコに連れてって TOKYO",
"triumphant song of promise at the end of the world": "世界の果てに約束の凱歌を -DDR Extended Megamix-",
"promised victory song": "世界の果てに約束の凱歌を -DDR Extended Megamix-",
"overdrive": "患部で止まってすぐ溶ける～狂気の優曇華院",
"stop at the affected area and melt quickly": "患部で止まってすぐ溶ける～狂気の優曇華院",
"usatei": "ウサテイ",
"myu myu mullru": "みゅ、みゅ、Müllる",
"rinne no karasu": "輪廻の鴉",
"galaxy on parchment": "羊皮紙の上の銀河",
"mentanpindoradora": "メンタンピンドラドラ",
"tokonyatsu tropical": "とこにゃつ☆トロピカル",
"nanahoshi": "ナナホシ",
"ladybug": "ナナホシ",
"scarlet police on ghetto patrol 24h": "スカーレット警察のゲットーパトロール24時",
"scarlet police on ghetto patrol": "スカーレット警察のゲットーパトロール24時",
"scarlet police": "スカーレット警察のゲットーパトロール24時",
"shinhebihime": "新蛇姫",
"new snake princess": "新蛇姫",
"perfect eater": "パーフェクトイーター",
"comet skater": "コメット⇒スケイター",
"hou": "鳳",
"phoenix": "鳳",
"loli god requiem": "粛聖!! ロリ神レクイエム☆",
"we are invincible idol": "我ら完全無敵のアイドル!!",
"hey ho neet": "悲報！ワイ！ニート！",
"girls band cry op": "雑踏、僕らの街",
"bad youth awake": "バッドユース・アウェイク",
"odore virtual animal": "踊れ！！バーチャルアニマル！！",
"romancing escape": "ロマンシングエスケープ",
"polar impact": "極地大衝撃",
"pupcore": "ポチコの幸せな日常",
"meikyoushisui": "明鏡止水",
"zen jass": "明鏡止水",
"zen jazz": "明鏡止水",
"sana molette ne ente": "サナ・モレッテ・ネ・エンテ",
"draw my feelings": "僕の気持ちを描く",
"legend of the foot god": "足神様ノ復活祭",
"cirnos perfect math class": "チルノのパーフェクトさんすう教室",
"cirno's perfect math class": "チルノのパーフェクトさんすう教室",
"bad apple": "Bad Apple!! feat. nomico",
"night of nights": "ナイト・オブ・ナイツ",
"knight of knights": "ナイト・オブ・ナイツ",
"night of knights": "ナイト・オブ・ナイツ",
"knight of nights": "ナイト・オブ・ナイツ",
"night of nights ryu": "ナイト・オブ・ナイツ (Ryu☆Remix)",
"knight of knights ryu": "ナイト・オブ・ナイツ (Ryu☆Remix)",
"night of knights ryu": "ナイト・オブ・ナイツ (Ryu☆Remix)",
"knight of nights ryu": "ナイト・オブ・ナイツ (Ryu☆Remix)",
"night of nights ryu remix": "ナイト・オブ・ナイツ (Ryu☆Remix)",
"knight of knights ryu remix": "ナイト・オブ・ナイツ (Ryu☆Remix)",
"night of knights ryu remix": "ナイト・オブ・ナイツ (Ryu☆Remix)",
"knight of nights ryu remix": "ナイト・オブ・ナイツ (Ryu☆Remix)",
"bad apple": "Bad Apple!! feat. nomico",
"announce spring": "春を告げる",
"flower": "FLOWER",
"king": "KING"
};